BIN := p_task1
BIN_2 := p_tree
SOURCES := p_task1.c 
SOURCES_2 := p_tree.c
HEADERS := 
CC := gcc
CFLAGS :=
LDFLAGS :=


$(BIN): $(SOURCES)
1:
		clear && $(CC) $(SOURCES) -o $(BIN) $(CFLAGS) $(LDFLAGS)
		./$(BIN)
$(BIN_2): $(SOURCES_2)
2:
		clear && $(CC) $(SOURCES_2) -o $(BIN_2) $(CFLAGS) $(LDFLAGS)
		./$(BIN_2)
cl:
		rm -rf $(BIN) $(BIN_2) && clear
