BIN := homework5
SOURCES := homework5.c
HEADERS := 
CC := gcc
CFLAGS :=
LDFLAGS := -lncurses

$(BIN): $(SOURCES)
		$(CC) $(SOURCES) -o $(BIN) $(CFLAGS) $(LDFLAGS)
b:		
		./$(BIN)		
$(BIN): $(HEADERS)

cl:
		rm -rf $(BIN) && clear
